var webstr = {
	"Home":"Home",
	"Analize":"Análisis", 
	"How":"¿Cómo funciona?",
	"FAQ": "FAQ",
	"Team": "Equipo",
	"Meteo-BI_Form": "Meteo-BI Form",
	"Renewable_Energy_Explorer": "Explorador de energía renovable",
	"Map":"Mapa",
	"Graphs":"Gráficos",
	"Yearly":"Anual",
	"Monthly":"Mensual",
	"Dayly":"Diario",
	"From":"Desde",
	"To":"Hasta",
	"Measure":"Medida",
	"Select_a_measure":"Seleccione una medida",
	"Horizontal_Solar_Radiation":"Radiación solar horizontal",
	"Dew_Frost":"Rocío, escarcha",
	"Relative_Humidity":"Humedad relativa",
	"Wind_Speed":"Velocidad del viento",
	"Precipitation":"PPrcipitaciones",
	"Temperature":"Temperatura",
	"Aggregator":"Aggregator",
	"Calculate":"Calcular"
	};