web.str = {
	"Home":"Home",
	"Analize":"Análisis", 
	"How does it work?":"¿Cómo funciona?",
	"FAQ": "FAQ",
	"Team": "Equipo",
	"Meteo-BI Form": "Meteo-BI Form",
	"Renewable Energy Explorer": "Explorador de energía renovable",
	"Map":"Mapa",
	"Graphs":"Gráficos",
	"Yearly":"Anual",
	"Monthly":"Mensual",
	"Dayly":"Diario",
	"From":"Desde",
	"To":"Hasta",
	"Measure":"Medida",
	"Select a measure":"Seleccione una medida",
	"Horizontal Solar Radiation":"Radiación solar horizontal",
	"Dew Frost":"Rocío, escarcha",
	"Relative Humidity":"Humedad relativa",
	"Wind Speed":"Velocidad del viento",
	"Precipitation":"PPrcipitaciones",
	"Temperature":"Temperatura",
	"Aggregator":"Aggregator",
	"Calculate":"Calcular"
	};