var webstr = {
	"Home":"Home",
	"Analize":"Analize", 
	"how":"How does it work?",
	"FAQ": "FAQ",
	"Team": "Team",
	"Meteo_BI_Form": "Meteo-BI Form",
	"Renewable_Energy_Explorer": "Renewable Energy Explorer",
	"Map":"Map",
	"Graphs":"Graphs",
	"Yearly":"Yearly",
	"Monthly":"Monthly",
	"Daily":"Dayly",
	"From":"From",
	"To":"To",
	"Measure":"Measure",
	"Select_a_measure":"Select a measure",
	"Horizontal_Solar_Radiation":"Horizontal Solar Radiation",
	"Dew_Frost":"Dew Frost",
	"Relative_Humidity":"Relative Humidity",
	"Wind_Speed":"Wind Speed",
	"Precipitation":"Precipitation",
	"Temperature":"Temperature",
	"Aggregator":"Aggregator",
	"Calculate":"Calculate"
	};