var webstr = {
	"Home":"Home",
	"Analize":"Análisis", 
	"How":"¿Cómo funciona?",
	"FAQ": "FAQ",
	"Team": "Equipo",
	"Meteo_BI_Form": "Meteo-BI Form",
	"Renewable_Energy_Explorer": "Explorador de energía renovable",
	"Map":"Mapa",
	"Graphs":"Gráficos",
	"Yearly":"Anual",
	"Monthly":"Mensual",
	"Daily":"Diario",
	"From":"Desde",
	"To":"Hasta",
	"Measure":"Tipo de medida",
	"Select_a_measure":"Seleccione una medida",
	"Horizontal_Solar_Radiation":"Radiación solar horizontal",
	"Dew_Frost":"Rocío, escarcha",
	"Relative_Humidity":"Humedad relativa",
	"Wind_Speed":"Velocidad del viento",
	"Precipitation":"Precipitaciones",
	"Temperature":"Temperatura",
	"Aggregator":"Agregado",
	"Calculate":"Calcular"
	};